### ISSUE TITLE
Hard-coded CredentialType?

### ISSUE THREAD

**Issue by kitakaze-kan** [OWND-Project/OWND-Wallet-iOS#9]
I am not sure, but CredentialType is hard-coded in Enum and forced unwrapped with the code below, which may cause an error if the CredentialType is not registered.

https://github.com/OWND-Project/OWND-Wallet-iOS/blob/484c7301495f5c49a83aa14a279bbdcdb759e1ba/tw2023_wallet/datastore/CredentialDataManager.swift#L156

**Comment by moratori** [comment]
@kitakaze-kan 
Thank you for creating an issue. As you pointed out, the current implementation only accepts certain credentials.
A wallet should be able to store a variety of credentials, so I have created a fix PR to remove this restriction.

**Comment by moratori** [comment]
The [PR](https://github.com/OWND-Project/OWND-Wallet-iOS/pull/12) resolving this issue has been merged.
